### PR TITLE
Solves differences between C++ and R estimation engines

### LINKED ISSUE #39: Preprocessing start-time and end-time bug
**Describe the bug**
The initialization of the stats matrices doesn't consider the start time argument.
This issue related to #33 

**To Reproduce**
```r
# direct network
eventsIncrement <- data.frame(
  time = cumsum(
    c(1, 5, 3, 4, 2, 1, 3, 4, 5, 1, 3, 4)),
  sender = sprintf("Actor %d",
    c(1, 3, 2, 2, 5, 1, 3, 3, 4, 2, 5, 1)),
  receiver = sprintf("Actor %d",
    c(2, 2, 3, 3, 1, 5, 4, 4, 2, 3, 2, 2)),
  increment =
    c(1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1),
  stringsAsFactors = FALSE
)

actorsEx <- data.frame(
  label = sprintf("Actor %d", 1:5),
  present = rep(TRUE, 5),
  attr1 = c(9.9, 0.1, 0.5, 0.45, 0.25),
  stringsAsFactors = FALSE
)

networkState <- matrix(
  c(0, 3, 0, 0, 0,
    1, 0, 1, 1, 0,
    0, 0, 0, 1, 0,
    0, 0, 1, 0, 0,
    0, 0, 0, 0, 0),
  nrow = 5, ncol = 5, byrow = TRUE,
  dimnames = list(sprintf("Actor %d", 1:5),
                  sprintf("Actor %d", 1:5))
)

# defining objects
networkState <- defineNetwork(
  matrix = networkState, nodes = actorsEx,
  directed = TRUE)
networkState <- linkEvents(
  x = networkState,
  changeEvent = eventsIncrement,
  nodes = actorsEx)
depNetwork <- defineDependentEvents(
  events = eventsIncrement,
  nodes = actorsEx,
  defaultNetwork = networkState)

prep <- estimate(depNetwork ~ inertia(networkState, window = 5,
                            preprocessOnly = TRUE,
                             estimationInit = list(startTime = 7))
prep$initialStats
```

**Expected behavior**

It should be an empty matrix

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - R Version 4.0.3
- Goldfish Version 1.5.0

### LINKED ISSUE #71: `C` and `R` engine results differ for rate model
**Describe the bug**
Default `C` engine gives different result as `R` version when windows effects are used.

**To Reproduce**

```r
library(goldfish)
data("Social_Evolution")

callNetwork <- defineNetwork(nodes = actors, directed = TRUE) |> # 1
  linkEvents(changeEvent = calls, nodes = actors) # 2

callsDependent <- defineDependentEvents(
  events = calls, nodes = actors,
  defaultNetwork = callNetwork
  )

windowFormulaRate <-
  callsDependent ~ 1 + indeg(callNetwork) + outdeg(callNetwork) +
                   indeg(callNetwork, window = 300) +
                   outdeg(callNetwork, window = 300) +
                   indeg(friendshipNetwork)

mod04Rate <- estimate(
  windowFormulaRate,
  model = "DyNAM", subModel = "rate",
  estimationInit = list(engine = "default_c")
)
mod04RateC <- coef(mod04Rate)

mod04Rate <- estimate(
  windowFormulaRate,
  model = "DyNAM", subModel = "rate"
)
mod04RateR <- coef(mod04Rate)

table(abs(mod04RateC - mod04RateR) < 1e-2)

> FALSE 
>     6
```

**Desktop (please complete the following information):**
 - OS: Windows
 - R Version 4.2.0
- Goldfish Version 1.6.2

### PR DESCRIPTION
**Pull request by auzaheta**
# Description

* Solves `startTime` and `endTime` bug on `DyNAM` and `REM` models
  preprocessing.
* Clean unnecessary functions imports.
* Solves `aes_string()` deprecation.
* Solves issue on `C++` engine on DyNAM-rate.
* Enforcing an 80-character line length on C++ code.
* Comply with code style.
* Changes that reduce execution time in the R estimation engine.

Fixes #71 
Closes #39 

# Checklist:

- [X] I have added tests that prove my fix is effective or that my feature works
- [X] The package builds on my OS without issues (please add workstation details)
- [X] My changes generate no new warnings
- [X] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (.R, NEWS.md)
- [X] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)

### CODE REVIEW

File: vignettes/dynami-example.R [hunk 1]
```diff
@@ -1,150 +1,179 @@
...
-## -----------------------------------------------------------------------------------------------------------
+## ----------------------------------------------------------------------------------------------------------------------
 library(goldfish)
 data("RFID_Validity_Study")
 #?RFID_Validity_Study
 
 
-## -----------------------------------------------------------------------------------------------------------
+## ----------------------------------------------------------------------------------------------------------------------
 head(participants)
```
Comment (jhollway) [inline vignettes/dynami-example.R:13]: I wonder whether we should change all these vignettes to tutorials. I think tutorials better fits how we use tutorials in courses, for example, and helps trim the size/testing burden of the package too. See [manynet](https://github.com/snlab-ch/manynet)/migraph for how we have done it there.

File: vignettes/teaching1.R [hunk 2]
```diff
@@ -101,14 +101,14 @@ autographr(callNetworkBgn, labels = FALSE, layout = "fr")
...
 
 autographr(callNetworkHlf, labels = FALSE, layout = "fr") +
   geom_node_point(aes(color = as.factor(floor)), size = 2, show.legend = FALSE)
 
 # The network at the end
-callNetworkEnd <- as.matrix(callNetwork, time = max(calls$time) + 1) |> 
+callNetworkEnd <- as.matrix(callNetwork, time = max(calls$time) + 1) |>
   add_node_attribute("floor", actors$floor)
 
 autographr(callNetworkEnd, labels = FALSE, layout = "fr") +
```
Comment (jhollway) [inline vignettes/teaching1.R:114]: Using vignettes means the plots will be changed everytime they are run, inflating the repository etc for no good reason. If they are illustrative, can they be moved to the README? If they are for learning/discovery, can they be in tutorials?

File: tests/testthat/test-effects_preprocessing_DyNAM_rate.R [hunk 3]
```diff
@@ -0,0 +1,365 @@
+test_that(
+  "out/in/deg weighted right censored preprocessing",
```
Comment (jhollway) [inline tests/testthat/test-effects_preprocessing_DyNAM_rate.R:2]: Excellent job adding all these very important tests, @auzaheta , thank you!

File: R/functions_diagnostics.R [hunk 4]
```diff
@@ -160,9 +164,6 @@ examineOutliers <- function(x,
 #' point sections identified by the method.
 # Also it prints a table of the change points events that are returned by the
 # method.
-#' @importFrom changepoint cpt.mean cpt.var
-#' @importFrom ggplot2 ggplot aes geom_line geom_point theme_minimal xlab ylab
-#'  geom_vline scale_x_continuous theme element_text
```
Comment (jhollway) [inline R/functions_diagnostics.R:165]: These still seem to be required below, e.g. lines 208 and 212

File: R/functions_effects_DyNAM_choice.R [hunk 5]
```diff
@@ -29,9 +29,8 @@ init_DyNAM_choice.default <- function(
   stats <- matrix(0, nrow = n1, ncol = n2) # check for poss
 
   # init a generic cache object
-  if ("cache" %in% .argsNames) {
-    cache <- stats
-  } else cache <- NULL
+  if ("cache" %in% .argsNames) cache <- stats
+  else cache <- NULL
```
Comment (jhollway) [inline R/functions_effects_DyNAM_choice.R:33]: If we are keen to use `{rlang}` as a dependency, there is also rlang::%||%, which might be useful here.

File: R/functions_group_interaction_utility.R [hunk 6]
```diff
@@ -52,7 +51,7 @@ defineGroups_interaction <- function(records, actors, seed.randomization,
   stopifnot(
     inherits(records, "data.frame"),
     inherits(actors, "data.frame"),
-    is(seed.randomization, "numeric"),
+    methods::is(seed.randomization, "numeric"),
```
Comment (jhollway) [inline R/functions_group_interaction_utility.R:54]: I think a methods dependency needs to be declared?
