### PR TITLE
Fixes CRAN comments

### LINKED ISSUE #10: Reduce size `result.goldfish`
The size of `result.goldfish` is increased when the formula is kept. The formula contains information of the parent environment.

### LINKED ISSUE #37: Choice-coordination wrong likelihood computation when nodes are not present
**Describe the bug**
Computation of the likelihood in the choice coordination doesn't exclude from the computation the nodes not present. 

**To Reproduce**
```r
# # observed relational events
eventsMM <- data.frame(
  time = cumsum(
    c(1, 5, 3, 4, 2)),
  sender = sprintf(
    "Actor %d", 
    c(1, 3, 2, 5, 5)),
  receiver = sprintf(
    "Actor %d", 
    c(2, 2, 4, 1, 1)),
  increment =
    c(1, 2, 1, 1, 1),
  stringsAsFactors = FALSE
)

# # actors attributes
actorsMM <- data.frame(
  label = sprintf("Actor %d", 1:5),
  present = c(rep(TRUE, 4), FALSE),
  # present = rep(TRUE, 5),
  attr1 = c(9.9, 0.1, 0.5, 0.45, 0.25),
  attr2 = c(1, 2, 1, 2, 1),
  stringsAsFactors = FALSE
)

# # actors change present
presentChange <- data.frame(
  time = 10,
  node = "Actor 5",
  replace = TRUE
)

# # state at the beginning of the network
networkMM <- matrix(
  c(0, 3, 2, 0, 0,
    3, 0, 0, 0, 0,
    2, 0, 0, 1, 0,
    0, 0, 1, 0, 0,
    0, 0, 0, 0, 0), 
  nrow = 5, ncol = 5, byrow = TRUE,
  dimnames = list(sprintf("Actor %d", 1:5),
                  sprintf("Actor %d", 1:5))
)

# defining objects
actorsMM <- defineNodes(actorsMM)
actorsMM <- linkEvents(actorsMM, changeEvents = presentChange, attribute = "present")
networkMM <- defineNetwork(
  matrix = networkMM, nodes = actorsMM,
  directed = FALSE)
networkMM <- linkEvents(
  x = networkMM,
  changeEvent = eventsMM,
  nodes = actorsMM)
depNetMM <- defineDependentEvents(
  events = eventsMM,
  nodes = actorsMM,
  defaultNetwork = networkMM)

# model
mod01 <- estimate(depNetMM ~ inertia + trans,
                  model = "DyNAM", subModel = "choice_coordination",
                  estimationInit = list(returnIntervalLogL = TRUE,
                                        returnEventProbabilities = TRUE),
                  verbose = TRUE)
```
```r
> Likelihood: -11.51293 in iteration 1 
> Parameters: 0, 0 
> Score: 0.25, -0.75
> Update: 0.00367483296213808, -0.0181514476614699
> Damping factor: 10
```

**Expected behavior**
The expected likelihood for the initial parameters `c(0, 0)` should be: `3 * log(1/6) + 2 * log(1/10)`. The first three events happen without "Actor 5", then the likelihood of a tie is 1 / choose(4,2) = 1/6. The last two with five nodes present, the likelihood of a tie is 1 / choose(5, 2) = 1/10. 

It computes `5 * log(1/10)`, which results when all nodes are present.

**Desktop:**
 - OS: Windows 10 Education
 - R Version 4.0.3
 - Goldfish Version 1.5.0

### LINKED ISSUE #67: Make sure exported/documented functions have associated \values
> Please add \value to .Rd files regarding exported methods and explain
> the functions results in the documentation. Please write about the
> structure of the output (class) and also what the output means.
> (If a function does not return a value, please document that too, e.g.
> \value{No return value, called for side effects} or similar)
> 
> Missing Rd-tags:
>        print-method.Rd: \value

### LINKED ISSUE #68: Add references to description description
> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available:<https:...>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
> auto-linking.
> (If you want to add a title as well please put it in quotes: "Title")

### LINKED ISSUE #69: Offer verbose options and/or S3 print methods
> You write information messages to the console that cannot be easily suppressed. It is more R like to generate objects that can be used to extract the information a user is interested in, and then print() that object.
> Instead of cat() rather use message()/warning()  or if(verbose)cat(..) (or maybe stop()) if you really have to write text to the console.
> (except for print, summary, interactive functions)

### LINKED ISSUE #70: Avoid relying on global environment
> Please do not modifiy the .GlobalEnv. This is not allowed by the CRAN policies.

### LINKED ISSUE #72: Call: in summary() includes just name of formula object

### PR DESCRIPTION
**Pull request by auzaheta**
# Description

It is a patch change. Improves documentation and replaces md formatting for rd formatting `Roxygen: list(markdown = TRUE)`. 

`logLik()` method aligns with packages `stats` output, new method `vcov()` is implemented. `result.goldfish` objects now can use methods `AIC()`, `BIC()`, `confint()` from the `stats` package and use the `lmtest::lrtest()` to compare nested models. `tidy()` now can retrieve also confidence interval limits, and with `compact = FALSE` will include arguments of effects calls as columns. 

Argument `silent` is dropped. Argument `verbose` allows printing minimal output to the console (former `silent`). Argument `debug` will give detailed information on parameter estimate changes during estimation (former `verbose`).

Drop date from the description file.

Vignettes drop `fig.retina` argument and do not modify the figures' size.

Fixes #10 
Fixes #37 
Closes #67  
Closes #68 
Fixes #69 
Fixes #70 
Fixes #72 

# Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] The package builds on my OS without issues (please add workstation details)
- [X] My changes generate no new warnings
- [X] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (.R, NEWS.md)
- [X] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)

### CODE REVIEW

File: R/functions_effects_DyNAM_choice.R [hunk 1]
```diff
@@ -167,7 +167,7 @@ init_DyNAM_choice.default <- function(
 #' @noRd
 #'
 #' @examples
-#' \dontrun{
+#' \donttest{
```
Comment (jhollway) [inline R/functions_effects_DyNAM_choice.R:170]: \donttest is still run as examples, perhaps takes too long for CRAN?

File: R/functions_effects_REM.R [hunk 2]
```diff
@@ -181,7 +181,7 @@ init_REM_choice.indeg <- function(effectFun, network, window, n1, n2) {
 #' @noRd
 #'
 #' @examples
-#' \dontrun{
+#' \donttest{
```
Comment (jhollway) [inline R/functions_effects_REM.R:184]: There are a bunch of conditional expressions in this script that codefactor is suggesting we use double `&&` for so that condition-matching occurs stepwise

File: R/functions_group_interaction_utility.R [hunk 3]
```diff
@@ -59,7 +73,8 @@ defineGroups_interaction <- function(records, actors, seed.randomization) {
 
   # STEP 1: order all events (start and end)
   # if some events occur at the same time, we randomize the order
-  # TODO: if events are close enough (<delta t), we also randomize when unperfect data
+  # TODO: if events are close enough (<delta t), we also randomize when
```
Comment (jhollway) [inline R/functions_group_interaction_utility.R:76]: Add this as an issue to track rather than in-code comment

File: R/functions_parsing.R [hunk 4]
```diff
@@ -514,32 +532,41 @@ parseMultipleEffects <- function(rhsNames, default = FALSE) {
...
     )
 
-    # # in the case windows is provided as an object name, it should start with alphabetic character
+    # # in the case windows is provided as an object name,
+    # it should start with alphabetic character
     isValidName <- grepl("^[[:alpha:]][[:alnum:]_.]+$", windowName)
 
     # support for lubridate object classes for date operations
-    if (inherits(window, c("Period", "Duration")) & "lubridate" %in% attr(attr(window, "class"), "package")) {
+    if (inherits(window, c("Period", "Duration")) &
```
Comment (jhollway) [inline R/functions_parsing.R:557]: `&&`?

File: R/functions_postestimate.R [hunk 5]
```diff
@@ -0,0 +1,120 @@
+
+#' Extract model coefficients from estimate output
```
Comment (jhollway) [inline R/functions_postestimate.R:2]: Can we add tests for these methods?

File: R/zzz.R [hunk 6]
```diff
@@ -3,10 +3,8 @@
   if (!interactive()) return()
   base::packageStartupMessage(
     "  <\")))><  The goldfish package in R\n\n",
-    pkgname, ": version ", utils::packageVersion("goldfish"),
-    ", \"Butterfly Tail\", created on ",
-    utils::packageDescription("goldfish", fields = "Date"),
```
Comment (jhollway) [inline R/zzz.R:8]: The date is useful for users, no?

File: R/functions_estimation.R [hunk 7]
```diff
@@ -307,19 +293,17 @@ estimate.formula <- function(
...
-      TriNAM = c("choice", "rate")
+      DyNAMi = c("choice", "rate")
     )
   )
 
   stopifnot(
     inherits(preprocessingOnly, "logical"),
     inherits(verbose, "logical"),
-    inherits(silent, "logical"),
     inherits(debug, "logical"),
```
Comment (jhollway) [inline R/functions_estimation.R:307]: Apparently `debug()` is undesirable...

File: R/functions_output.R [hunk 8]
```diff
@@ -1,124 +1,33 @@
 ######################### ###
 #
-# Print, summary and xtable functions
+# Print and summary functions
```
Comment (jhollway) [inline R/functions_output.R:3]: Alternatively, we could just tidy print straight away?

**Review by jhollway — COMMENTED** [review]
Great work @auzaheta !

File: R/functions_output.R (hunk 8 above)
Comment (auzaheta) [reply R/functions_output.R:3]: I don't follow this one

File: R/functions_estimation.R (hunk 7 above)
Comment (auzaheta) [reply R/functions_estimation.R:307]: The easiest is to change the name of the argument. We already use `verbose` for printing the messages during estimation.
`debug` prints the coefficients, log-likelihood, and score change after every iteration. Any suggestions for a better name

File: R/functions_group_interaction_utility.R (hunk 3 above)
Comment (auzaheta) [reply R/functions_group_interaction_utility.R:76]: @marion-hoffman, thoughs?

File: R/functions_effects_DyNAM_choice.R (hunk 1 above)
Comment (auzaheta) [reply R/functions_effects_DyNAM_choice.R:170]: I'll be worried about the examples in `estimate()`. In the effects files, the examples expend less than a second. Did you find one that takes too long to run here?

File: R/functions_output.R (hunk 8 above)
Comment (jhollway) [reply R/functions_output.R:3]: That is, make the default printing the tidy printing.

File: R/functions_estimation.R (hunk 7 above)
Comment (jhollway) [reply R/functions_estimation.R:307]: Why not `messages` and `verbose`, or `verbose` and `updates`?

File: R/functions_effects_DyNAM_choice.R (hunk 1 above)
Comment (jhollway) [reply R/functions_effects_DyNAM_choice.R:170]: Let's try it then.

File: R/functions_estimation.R (hunk 7 above)
Comment (auzaheta) [reply R/functions_estimation.R:307]: `?optimHess` uses `trace`. What about `verbose` and `trace`?

Comment (jhollway) [reply R/functions_estimation.R:307]: trace could work, but could be confusing if we then talk about trace diagnostics? Another option for the former would be `progress`?

File: R/functions_output.R (hunk 8 above)
Comment (auzaheta) [reply R/functions_output.R:3]: Right now `tidy()` uses `summary()` to get the `coefMat` matrix.

I prefer to keep it like it's now.

File: R/functions_estimation.R (hunk 7 above)
Comment (auzaheta) [reply R/functions_estimation.R]: Done in [efb815f](https://github.com/snlab-ch/goldfish/pull/77/commits/efb815fde17ae6643e98bc282790cef0bd725438)

File: R/zzz.R (hunk 6 above)
Comment (auzaheta) [reply R/zzz.R:8]: Done in [efb815f](https://github.com/snlab-ch/goldfish/pull/77/commits/efb815fde17ae6643e98bc282790cef0bd725438)

File: R/functions_effects_REM.R (hunk 2 above)
Comment (auzaheta) [reply R/functions_effects_REM.R:184]: Done in [5fcd81c](https://github.com/snlab-ch/goldfish/pull/77/commits/5fcd81cff3c44c9fbf950afc14b548ae1defb66c)

File: R/functions_postestimate.R (hunk 5 above)
Comment (auzaheta) [reply R/functions_postestimate.R:2]: Done in [1c5ce54](https://github.com/snlab-ch/goldfish/pull/77/commits/1c5ce54d4414f4656aad101aa475fa9b7a2c80d0)

**Comment by auzaheta** [comment]
@jhollway and @marion-hoffman, I think there are no more comments for this pull request.
Let me know otherwise.

**Comment by marion-hoffman** [comment]
For me it seems to work fine and all my urgent to-dos are done :)

**Review by jhollway — APPROVED** [review]
Looks good -- if you `devtools::submit_cran()`, I'll confirm the email and we'll see what CRAN says
